from __future__ import annotations

CANDIDATE_DISCOVERED = "DISCOVERED"
CANDIDATE_REJECTED = "REJECTED"
CANDIDATE_NEED_WEIGHT = "NEED_WEIGHT"
CANDIDATE_NEED_SITE_INDEX = "NEED_SITE_INDEX"
CANDIDATE_QUALIFIED = "QUALIFIED"
CANDIDATE_PROMOTED = "PROMOTED"

CANDIDATE_STATUSES = {
    CANDIDATE_DISCOVERED,
    CANDIDATE_REJECTED,
    CANDIDATE_NEED_WEIGHT,
    CANDIDATE_NEED_SITE_INDEX,
    CANDIDATE_QUALIFIED,
    CANDIDATE_PROMOTED,
}
